package org.apache.catalina;
import java.beans.PropertyChangeListener;
import java.io.File;
import javax.management.ObjectName;
import org.apache.catalina.connector.Request;
import org.apache.catalina.connector.Response;
import org.apache.juli.logging.Log;
public interface Container extends Lifecycle {
    public static final String ADD_CHILD_EVENT = "addChild";
    public static final String ADD_VALVE_EVENT = "addValve";
    public static final String REMOVE_CHILD_EVENT = "removeChild";
    public static final String REMOVE_VALVE_EVENT = "removeValve";
    public Log getLogger();
    public String getLogName();
    public ObjectName getObjectName();
    public String getDomain();
    public String getMBeanKeyProperties();
    public Pipeline getPipeline();
    public Cluster getCluster();
    public void setCluster ( Cluster cluster );
    public int getBackgroundProcessorDelay();
    public void setBackgroundProcessorDelay ( int delay );
    public String getName();
    public void setName ( String name );
    public Container getParent();
    public void setParent ( Container container );
    public ClassLoader getParentClassLoader();
    public void setParentClassLoader ( ClassLoader parent );
    public Realm getRealm();
    public void setRealm ( Realm realm );
    public void backgroundProcess();
    public void addChild ( Container child );
    public void addContainerListener ( ContainerListener listener );
    public void addPropertyChangeListener ( PropertyChangeListener listener );
    public Container findChild ( String name );
    public Container[] findChildren();
    public ContainerListener[] findContainerListeners();
    public void removeChild ( Container child );
    public void removeContainerListener ( ContainerListener listener );
    public void removePropertyChangeListener ( PropertyChangeListener listener );
    public void fireContainerEvent ( String type, Object data );
    public void logAccess ( Request request, Response response, long time,
                            boolean useDefault );
    public AccessLog getAccessLog();
    public int getStartStopThreads();
    public void setStartStopThreads ( int startStopThreads );
    public File getCatalinaBase();
    public File getCatalinaHome();
}
