package org.apache.tomcat.jdbc.pool;
import java.util.Properties;
import org.apache.tomcat.jdbc.pool.PoolProperties.InterceptorDefinition;
public interface PoolConfiguration {
    public static final String PKG_PREFIX = "org.apache.tomcat.jdbc.pool.interceptor.";
    public void setAbandonWhenPercentageFull ( int percentage );
    public int getAbandonWhenPercentageFull();
    public boolean isFairQueue();
    public void setFairQueue ( boolean fairQueue );
    public boolean isAccessToUnderlyingConnectionAllowed();
    public void setAccessToUnderlyingConnectionAllowed ( boolean accessToUnderlyingConnectionAllowed );
    public String getConnectionProperties();
    public void setConnectionProperties ( String connectionProperties );
    public Properties getDbProperties();
    public void setDbProperties ( Properties dbProperties );
    public Boolean isDefaultAutoCommit();
    public Boolean getDefaultAutoCommit();
    public void setDefaultAutoCommit ( Boolean defaultAutoCommit );
    public String getDefaultCatalog();
    public void setDefaultCatalog ( String defaultCatalog );
    public Boolean isDefaultReadOnly();
    public Boolean getDefaultReadOnly();
    public void setDefaultReadOnly ( Boolean defaultReadOnly );
    public int getDefaultTransactionIsolation();
    public void setDefaultTransactionIsolation ( int defaultTransactionIsolation );
    public String getDriverClassName();
    public void setDriverClassName ( String driverClassName );
    public int getInitialSize();
    public void setInitialSize ( int initialSize );
    public boolean isLogAbandoned();
    public void setLogAbandoned ( boolean logAbandoned );
    public int getMaxActive();
    public void setMaxActive ( int maxActive );
    public int getMaxIdle();
    public void setMaxIdle ( int maxIdle );
    public int getMaxWait();
    public void setMaxWait ( int maxWait );
    public int getMinEvictableIdleTimeMillis();
    public void setMinEvictableIdleTimeMillis ( int minEvictableIdleTimeMillis );
    public int getMinIdle();
    public void setMinIdle ( int minIdle );
    public String getName();
    public void setName ( String name );
    public int getNumTestsPerEvictionRun();
    public void setNumTestsPerEvictionRun ( int numTestsPerEvictionRun );
    public String getPassword();
    public void setPassword ( String password );
    public String getPoolName();
    public String getUsername();
    public void setUsername ( String username );
    public boolean isRemoveAbandoned();
    public void setRemoveAbandoned ( boolean removeAbandoned );
    public void setRemoveAbandonedTimeout ( int removeAbandonedTimeout );
    public int getRemoveAbandonedTimeout();
    public boolean isTestOnBorrow();
    public void setTestOnBorrow ( boolean testOnBorrow );
    public boolean isTestOnReturn();
    public void setTestOnReturn ( boolean testOnReturn );
    public boolean isTestWhileIdle();
    public void setTestWhileIdle ( boolean testWhileIdle );
    public int getTimeBetweenEvictionRunsMillis();
    public void setTimeBetweenEvictionRunsMillis ( int timeBetweenEvictionRunsMillis );
    public String getUrl();
    public void setUrl ( String url );
    public String getValidationQuery();
    public void setValidationQuery ( String validationQuery );
    public int getValidationQueryTimeout();
    public void setValidationQueryTimeout ( int validationQueryTimeout );
    public String getValidatorClassName();
    public void setValidatorClassName ( String className );
    public Validator getValidator();
    public void setValidator ( Validator validator );
    public long getValidationInterval();
    public void setValidationInterval ( long validationInterval );
    public String getInitSQL();
    public void setInitSQL ( String initSQL );
    public boolean isTestOnConnect();
    public void setTestOnConnect ( boolean testOnConnect );
    public String getJdbcInterceptors();
    public void setJdbcInterceptors ( String jdbcInterceptors );
    public InterceptorDefinition[] getJdbcInterceptorsAsArray();
    public boolean isJmxEnabled();
    public void setJmxEnabled ( boolean jmxEnabled );
    public boolean isPoolSweeperEnabled();
    public boolean isUseEquals();
    public void setUseEquals ( boolean useEquals );
    public long getMaxAge();
    public void setMaxAge ( long maxAge );
    public boolean getUseLock();
    public void setUseLock ( boolean useLock );
    public void setSuspectTimeout ( int seconds );
    public int getSuspectTimeout();
    public void setDataSource ( Object ds );
    public Object getDataSource();
    public void setDataSourceJNDI ( String jndiDS );
    public String getDataSourceJNDI();
    public boolean isAlternateUsernameAllowed();
    public void setAlternateUsernameAllowed ( boolean alternateUsernameAllowed );
    public void setCommitOnReturn ( boolean commitOnReturn );
    public boolean getCommitOnReturn();
    public void setRollbackOnReturn ( boolean rollbackOnReturn );
    public boolean getRollbackOnReturn();
    public void setUseDisposableConnectionFacade ( boolean useDisposableConnectionFacade );
    public boolean getUseDisposableConnectionFacade();
    public void setLogValidationErrors ( boolean logValidationErrors );
    public boolean getLogValidationErrors();
    public boolean getPropagateInterruptState();
    public void setPropagateInterruptState ( boolean propagateInterruptState );
    public void setIgnoreExceptionOnPreLoad ( boolean ignoreExceptionOnPreLoad );
    public boolean isIgnoreExceptionOnPreLoad();
}
