package org.apache.tomcat.jni;
import java.nio.ByteBuffer;
public class File {
    public static final int APR_FOPEN_READ       = 0x00001;
    public static final int APR_FOPEN_WRITE      = 0x00002;
    public static final int APR_FOPEN_CREATE     = 0x00004;
    public static final int APR_FOPEN_APPEND     = 0x00008;
    public static final int APR_FOPEN_TRUNCATE   = 0x00010;
    public static final int APR_FOPEN_BINARY     = 0x00020;
    public static final int APR_FOPEN_EXCL       = 0x00040;
    public static final int APR_FOPEN_BUFFERED   = 0x00080;
    public static final int APR_FOPEN_DELONCLOSE = 0x00100;
    public static final int APR_FOPEN_XTHREAD     = 0x00200;
    public static final int APR_FOPEN_SHARELOCK   = 0x00400;
    public static final int APR_FOPEN_NOCLEANUP   = 0x00800;
    public static final int APR_FOPEN_SENDFILE_ENABLED = 0x01000;
    public static final int APR_FOPEN_LARGEFILE      = 0x04000;
    public static final int APR_SET = 0;
    public static final int APR_CUR = 1;
    public static final int APR_END = 2;
    public static final int APR_FILE_ATTR_READONLY   = 0x01;
    public static final int APR_FILE_ATTR_EXECUTABLE = 0x02;
    public static final int APR_FILE_ATTR_HIDDEN     = 0x04;
    public static final int APR_FLOCK_SHARED    = 1;
    public static final int APR_FLOCK_EXCLUSIVE = 2;
    public static final int APR_FLOCK_TYPEMASK  = 0x000F;
    public static final int APR_FLOCK_NONBLOCK  = 0x0010;
    public static final int APR_NOFILE  = 0;
    public static final int APR_REG     = 1;
    public static final int APR_DIR     = 2;
    public static final int APR_CHR     = 3;
    public static final int APR_BLK     = 4;
    public static final int APR_PIPE    = 5;
    public static final int APR_LNK     = 6;
    public static final int APR_SOCK    = 7;
    public static final int APR_UNKFILE = 127;
    public static final int APR_FPROT_USETID     = 0x8000;
    public static final int APR_FPROT_UREAD      = 0x0400;
    public static final int APR_FPROT_UWRITE     = 0x0200;
    public static final int APR_FPROT_UEXECUTE   = 0x0100;
    public static final int APR_FPROT_GSETID     = 0x4000;
    public static final int APR_FPROT_GREAD      = 0x0040;
    public static final int APR_FPROT_GWRITE     = 0x0020;
    public static final int APR_FPROT_GEXECUTE   = 0x0010;
    public static final int APR_FPROT_WSTICKY    = 0x2000;
    public static final int APR_FPROT_WREAD      = 0x0004;
    public static final int APR_FPROT_WWRITE     = 0x0002;
    public static final int APR_FPROT_WEXECUTE   = 0x0001;
    public static final int APR_FPROT_OS_DEFAULT = 0x0FFF;
    public static final int APR_FINFO_LINK   = 0x00000001;
    public static final int APR_FINFO_MTIME  = 0x00000010;
    public static final int APR_FINFO_CTIME  = 0x00000020;
    public static final int APR_FINFO_ATIME  = 0x00000040;
    public static final int APR_FINFO_SIZE   = 0x00000100;
    public static final int APR_FINFO_CSIZE  = 0x00000200;
    public static final int APR_FINFO_DEV    = 0x00001000;
    public static final int APR_FINFO_INODE  = 0x00002000;
    public static final int APR_FINFO_NLINK  = 0x00004000;
    public static final int APR_FINFO_TYPE   = 0x00008000;
    public static final int APR_FINFO_USER   = 0x00010000;
    public static final int APR_FINFO_GROUP  = 0x00020000;
    public static final int APR_FINFO_UPROT  = 0x00100000;
    public static final int APR_FINFO_GPROT  = 0x00200000;
    public static final int APR_FINFO_WPROT  = 0x00400000;
    public static final int APR_FINFO_ICASE  = 0x01000000;
    public static final int APR_FINFO_NAME   = 0x02000000;
    public static final int APR_FINFO_MIN    = 0x00008170;
    public static final int APR_FINFO_IDENT  = 0x00003000;
    public static final int APR_FINFO_OWNER  = 0x00030000;
    public static final int APR_FINFO_PROT   = 0x00700000;
    public static final int APR_FINFO_NORM   = 0x0073b170;
    public static final int APR_FINFO_DIRENT = 0x02000000;
    public static native long open ( String fname, int flag, int perm, long pool )
    throws Error;
    public static native int close ( long file );
    public static native int flush ( long thefile );
    public static native long mktemp ( String templ, int flags, long pool )
    throws Error;
    public static native int remove ( String path, long pool );
    public static native int rename ( String fromPath, String toPath, long pool );
    public static native int copy ( String fromPath, String toPath, int perms, long pool );
    public static native int append ( String fromPath, String toPath, int perms, long pool );
    public static native int puts ( byte [] str, long thefile );
    public static native long seek ( long thefile, int where, long offset )
    throws Error;
    public static native int putc ( byte ch, long thefile );
    public static native int ungetc ( byte ch, long thefile );
    public static native int write ( long thefile, byte[] buf, int offset, int nbytes );
    public static native int writeb ( long thefile, ByteBuffer buf, int offset, int nbytes );
    public static native int writeFull ( long thefile, byte[] buf, int offset, int nbytes );
    public static native int writeFullb ( long thefile, ByteBuffer buf, int offset, int nbytes );
    public static native int writev ( long thefile, byte[][] vec );
    public static native int writevFull ( long thefile, byte[][] vec );
    public static native int read ( long thefile, byte[] buf,  int offset, int nbytes );
    public static native int readb ( long thefile, ByteBuffer buf,  int offset, int nbytes );
    public static native int readFull ( long thefile, byte[] buf,  int offset, int nbytes );
    public static native int readFullb ( long thefile, ByteBuffer buf,  int offset, int nbytes );
    public static native int gets ( byte[] buf,  int offset, long thefile );
    public static native int getc ( long thefile )
    throws Error;
    public static native int eof ( long fptr );
    public static native String nameGet ( long thefile );
    public static native int permsSet ( String fname, int perms );
    public static native int  attrsSet ( String fname, int attributes, int mask, long pool );
    public static native int  mtimeSet ( String fname, long mtime, long pool );
    public static native int lock ( long thefile, int type );
    public static native int unlock ( long thefile );
    public static native int flagsGet ( long file );
    public static native int trunc ( long fp, long offset );
    public static native int pipeCreate ( long [] io, long pool );
    public static native long pipeTimeoutGet ( long thepipe )
    throws Error;
    public static native int pipeTimeoutSet ( long thepipe, long timeout );
    public static native long dup ( long newFile, long oldFile, long pool )
    throws Error;
    public static native int dup2 ( long newFile, long oldFile, long pool );
    public static native int stat ( FileInfo finfo, String fname, int wanted, long pool );
    public static native FileInfo getStat ( String fname, int wanted, long pool );
    public static native int infoGet ( FileInfo finfo, int wanted, long thefile );
    public static native FileInfo getInfo ( int wanted, long thefile );
}
